version: '3.8'

services:
  api:
    container_name: federation-api
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - environment.env
    depends_on:
      - mariadb
    networks:
      - rede-db

  mariadb:
    image: mariadb:11.3
    container_name: federation-maria-db-11_3
    env_file:
      - environment.env
    ports:
      - "3306:3306"
    networks:
      - rede-db
    volumes:
      - "./data:/var/lib/mysql"

networks:
  rede-db:
    driver: bridge