CREATE SEQUENCE IF NOT EXISTS seq_id START WITH 1;
CREATE SEQUENCE IF NOT EXISTS seq_id_state START WITH 1;

CREATE TABLE COUNTRIES
(
    ID          VARCHAR(36) NOT NULL UNIQUE PRIMARY KEY,
    NAME        VARCHAR(100),
    CODE        VARCHAR(6),
    DESCRIPTION VARCHAR(255),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    PRIMARY KEY (ID)
);

CREATE TABLE STATE
(
    ID          VARCHAR(36) NOT NULL UNIQUE PRIMARY KEY ,
    NAME        VARCHAR(100),
    CODE        VARCHAR(6),
    DESCRIPTION VARCHAR(255),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    COUNTRY_ID VARCHAR(36),
    PRIMARY KEY (ID),
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(ID)
);